

name: Deploy
on:
 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout
        uses: actions/checkout@v2
                   
      - name: Lint code
        run: echo "Linting repository!"

      - name: Run unit tests
        run: |
          echo "Running unit tests"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: terraform
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - run: aws --version
        shell: bash
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
         version: v1.3.7
         run: |
          terraform init
          terraform apply -auto-approve
      - name: pull  image to ec2
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.PUBLIC_KEY }}
         username: ubuntu
         key: ${{ secrets.PRIVATE_KEY }}
         run:
           sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           sudo docker ps
           

       

